export { default as html_icon } from "./html-icon.png";
export { default as css_icon } from "./css-icon.png";
export { default as java_script_icon } from "./java-script-icon.png";
export { default as type_script_icon } from "./type-script-icon.png";
export { default as react_icon } from "./react-icon.png";
export { default as vite_icon } from "./vite-icon.png";
export { default as next_icon } from "./next-js-icon.png";
export { default as node_icon } from "./node-js-icon.png";
export { default as scss_icon } from "./scss-icon.png";
